[
    {
        "repo_name": "openSUSE/libsolv",
        "CVE_ID": "CVE-2018-20532",
        "Problem_Type": "CWE-476",
        "Description": "There is a NULL pointer dereference at ext/testcase.c (function testcase_read) in libsolvext.a in libsolv through 0.7.2 that will cause a denial of service.",
        "URL": "https://github.com/openSUSE/libsolv/pull/291",
        "Tag": "['Patch', 'Third Party Advisory']",
        "fix_commit_hash": "4830af9d979d3685de538b80fbeba51ad590525e",
        "inducing_commit_hash_pyszz": [],
        "inducing_commit_hash_pd": [],
        "matched": []
    },
    {
        "repo_name": "openSUSE/libsolv",
        "CVE_ID": "CVE-2018-20534",
        "Problem_Type": "CWE-119",
        "Description": "There is an illegal address access at ext/testcase.c in libsolv.a in libsolv through 0.7.2 that will cause a denial of service. NOTE: third parties dispute this issue stating that the issue affects the test suite and not the underlying library. It cannot be exploited in any real-world application",
        "URL": "https://github.com/openSUSE/libsolv/pull/291",
        "Tag": "['Patch', 'Third Party Advisory']",
        "fix_commit_hash": "4830af9d979d3685de538b80fbeba51ad590525e",
        "inducing_commit_hash_pyszz": [],
        "inducing_commit_hash_pd": [],
        "matched": []
    },
    {
        "repo_name": "openSUSE/libsolv",
        "CVE_ID": "CVE-2018-20533",
        "Problem_Type": "CWE-476",
        "Description": "There is a NULL pointer dereference at ext/testcase.c (function testcase_str2dep_complex) in libsolvext.a in libsolv through 0.7.2 that will cause a denial of service.",
        "URL": "https://github.com/openSUSE/libsolv/pull/291",
        "Tag": "['Patch', 'Third Party Advisory']",
        "fix_commit_hash": "4830af9d979d3685de538b80fbeba51ad590525e",
        "inducing_commit_hash_pyszz": [],
        "inducing_commit_hash_pd": [],
        "matched": []
    }
]