[
    {
        "repo_name": "py-pdf/pypdf",
        "CVE_ID": "CVE-2023-36464",
        "Problem_Type": "CWE-835",
        "Description": "pypdf is an open source, pure-python PDF library. In affected versions an attacker may craft a PDF which leads to an infinite loop if `__parse_content_stream` is executed. That is, for example, the case if the user extracted text from such a PDF. This issue was introduced in pull request #969 and resolved in pull request #1828. Users are advised to upgrade. Users unable to upgrade may modify the line `while peek not in (b\"\\r\", b\"\\n\")` in `pypdf/generic/_data_structures.py` to `while peek not in (b\"\\r\", b\"\\n\", b\"\")`.",
        "URL": "https://github.com/py-pdf/pypdf/pull/969",
        "Tag": "['Issue Tracking', 'Patch']",
        "fix_commit_hash": "72fcaae50e9676ca16346a556c29b688ae2714f8",
        "inducing_commit_hash_pyszz": [
            "41eff2a059ee4f4a9cbca931a110e65a3521bcd7"
        ],
        "inducing_commit_hash_pd": [
            "7647ab5f35f386050943fbe1be74351d8e5aac91",
            "b4d54ed59486abfcd429a281c4d12cc09780636b",
            "869c626074017195d506c977c52840feed874caf",
            "50e9079ae60f19c543b4c147369e988ad2edfe7c",
            "e38b23d40fcfedbbe09d9d9d8590a05d55c286ee",
            "648e3083314360444e3c03e7dd14834beb89538a",
            "5703b61b4232cbd44eed8689da604347e29bb51b",
            "cfe2d036e5e95d7cf1480e2518d814d1eaa35298",
            "bcafcff11374e11abaaf6608eb5715bc9a7dff59",
            "c66ee8cf01a9ef5984bdc5a8eb612227ede413ab",
            "4baedb2054648b9db70c2fbed82b6902aea52365",
            "6e14d3eeeef58cd1a48ace85211d217f2f9e8fad",
            "787c784c5ec1c68737717321204943071722e8dc",
            "1f0079401495ea94ff5b838b3e41412dc44c2c1d",
            "4429066367248fc4786a0d3c6ba59427b4b8bf63",
            "41eff2a059ee4f4a9cbca931a110e65a3521bcd7",
            "304d9ff223641b8425b3f8548d7826fb089adcb4",
            "eef03d935dfeacaa75848b39082cf94d833d3174",
            "833900060d7d9f1b3de18a4266d110394ad4264c",
            "8cd0cfe17c34c0fea89a94a92af7f061e67831ec",
            "57301980b8c44273a53d42ea4041ff7d73697f6f",
            "e1408f7488f2df54341b1208f2ad0a1b14eb8e81",
            "43276ab5002e37cd2c654cdbe67bbfa0b1fe2eb3",
            "38417347e86f2ca5ceb650a50a5a6200bfd97340",
            "b387b06718c5347ea641b06acd44ee636b7ca864",
            "9947c7b51f9e413458cc91eca2a1250829662fea",
            "d990367334964f8758857eaa266a82ee4bd49cb7",
            "94952e48b28c3eb31a572c092ffded643e8c5310",
            "fe403981046fee86321ff0f09ffe5ba38d05d27f",
            "444fca22836df061d9d23e71ffb7d68edcdfa766",
            "a5d68957dfdfdced04fb0fed1f1416266c65759e",
            "d659966f927ef5bd2559f9c658d30d5723ad4fc8",
            "0f0f7d65c93ef5ebd757b7476838d84085e0c25e",
            "b76ffcda07ae1c447bf3319e182b41ebf6d2057c",
            "a7dc37078012f7a4497d8e5fb3e34da647790c9e",
            "38d5ec462eb64cd686440716cae9c57dbb8e27d0",
            "e853ec1b65ee6b5c761289292b3b2835ec2f4320",
            "1f0fbf3267d34aad3405b17deb461459ec26559e",
            "012709f7a145d1fd85c3f6ca2a8e4c792d14e94b",
            "c008b0f448219d4727a8ba07570aba0abf4321e2",
            "f74d733ae5e93b2fa73e912754c9158f6018d851",
            "55f7c7b35be4431336a8c5a769a7c261445bd47a",
            "2867d77970118b595e03669aecf0041036125497",
            "97c55d4612adce6ee70a5df008c13db4840be6d9",
            "60dff8d785dcd4bea20be35b0f6a249ba4d44216",
            "c59a212a4cda512c184a987312970b464404d17b",
            "336d659c41dca4bce9554f70a8586fb1450dd676",
            "07bb859e91ce61d053a7abd3eac71665d92e10b7"
        ],
        "matched": [
            "41eff2a059ee4f4a9cbca931a110e65a3521bcd7"
        ]
    },
    {
        "repo_name": "py-pdf/pypdf",
        "CVE_ID": "CVE-2023-36464",
        "Problem_Type": "CWE-835",
        "Description": "pypdf is an open source, pure-python PDF library. In affected versions an attacker may craft a PDF which leads to an infinite loop if `__parse_content_stream` is executed. That is, for example, the case if the user extracted text from such a PDF. This issue was introduced in pull request #969 and resolved in pull request #1828. Users are advised to upgrade. Users unable to upgrade may modify the line `while peek not in (b\"\\r\", b\"\\n\")` in `pypdf/generic/_data_structures.py` to `while peek not in (b\"\\r\", b\"\\n\", b\"\")`.",
        "URL": "https://github.com/py-pdf/pypdf/pull/1828",
        "Tag": "['Patch']",
        "fix_commit_hash": "b0e5c689df689ab173df84dacd77b6fc3c161932",
        "inducing_commit_hash_pyszz": [
            "a85148ae83033de50e59dae7ca621305bb53ef6a"
        ],
        "inducing_commit_hash_pd": [
            "a85148ae83033de50e59dae7ca621305bb53ef6a"
        ],
        "matched": [
            "a85148ae83033de50e59dae7ca621305bb53ef6a"
        ]
    },
    {
        "repo_name": "py-pdf/pypdf",
        "CVE_ID": "CVE-2023-36807",
        "Problem_Type": "CWE-835",
        "Description": "pypdf is a pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. In version 2.10.5 an attacker who uses this vulnerability can craft a PDF which leads to an infinite loop. This infinite loop blocks the current process and can utilize a single core of the CPU by 100%. It does not affect memory usage. That is, for example, the case if the user extracted metadata from such a malformed PDF. Versions prior to 2.10.5 throw an error, but do not hang forever. This issue was fixed with https://github.com/py-pdf/pypdf/pull/1331 which has been included in release 2.10.6. Users are advised to upgrade. Users unable to upgrade should modify `PyPDF2/generic/_data_structures.py::read_object` to an an error throwing case. See GHSA-hm9v-vj3r-r55m for details. ",
        "URL": "https://github.com/py-pdf/pypdf/pull/1331",
        "Tag": "['Patch']",
        "fix_commit_hash": "e6531a25325e7e0174b6a1ba03b57320b5227f6b",
        "inducing_commit_hash_pyszz": [
            "a85148ae83033de50e59dae7ca621305bb53ef6a"
        ],
        "inducing_commit_hash_pd": [
            "2c53813dfac9791f639a2e6517cba1feb2671c32",
            "a85148ae83033de50e59dae7ca621305bb53ef6a"
        ],
        "matched": [
            "a85148ae83033de50e59dae7ca621305bb53ef6a"
        ]
    },
    {
        "repo_name": "py-pdf/pypdf",
        "CVE_ID": "CVE-2023-36810",
        "Problem_Type": "CWE-407",
        "Description": "pypdf is a pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files. An attacker who uses this vulnerability can craft a PDF which leads to unexpected long runtime. This quadratic runtime blocks the current process and can utilize a single core of the CPU by 100%. It does not affect memory usage. This issue has been addressed in PR 808 and versions from 1.27.9 include this fix. Users are advised to upgrade. There are no known workarounds for this vulnerability.",
        "URL": "https://github.com/py-pdf/pypdf/pull/808",
        "Tag": "['Patch']",
        "fix_commit_hash": "c6c56f550bb384e05f0139c796ba1308837d6373",
        "inducing_commit_hash_pyszz": [
            "793be4355bc276963b4a527d04c6588d4e4d42a3"
        ],
        "inducing_commit_hash_pd": [
            "c59a212a4cda512c184a987312970b464404d17b",
            "793be4355bc276963b4a527d04c6588d4e4d42a3",
            "bcafcff11374e11abaaf6608eb5715bc9a7dff59"
        ],
        "matched": [
            "793be4355bc276963b4a527d04c6588d4e4d42a3"
        ]
    },
    {
        "repo_name": "py-pdf/pypdf",
        "CVE_ID": "CVE-2023-46250",
        "Problem_Type": "CWE-835",
        "Description": "pypdf is a free and open-source pure-python PDF library. An attacker who uses a vulnerability present in versions 3.7.0 through 3.16.4 can craft a PDF which leads to an infinite loop. This infinite loop blocks the current process and can utilize a single core of the CPU by 100%. It does not affect memory usage. That is, for example, the case when the pypdf-user manipulates an incoming malicious PDF e.g. by merging it with another PDF or by adding annotations. The issue was fixed in version 3.17.0. As a workaround, apply the patch manually by modifying `pypdf/generic/_data_structures.py`.",
        "URL": "https://github.com/py-pdf/pypdf/pull/2264",
        "Tag": "['Issue Tracking', 'Patch']",
        "fix_commit_hash": "9b23ac3c9619492570011d551d521690de9a3e2d",
        "inducing_commit_hash_pyszz": [
            "39f52dceaef6b980d1e0e36214e373a97fb1fd15"
        ],
        "inducing_commit_hash_pd": [
            "74b8a6364ee806cc0510b024864502d1fdbd8204",
            "39f52dceaef6b980d1e0e36214e373a97fb1fd15"
        ],
        "matched": [
            "39f52dceaef6b980d1e0e36214e373a97fb1fd15"
        ]
    }
]