[
    {
        "repo_name": "abhinavsingh/proxy.py",
        "CVE_ID": "CVE-2021-3116",
        "Problem_Type": "CWE-697",
        "Description": "before_upstream_connection in AuthPlugin in http/proxy/auth.py in proxy.py before 2.3.1 accepts incorrect Proxy-Authorization header data because of a boolean confusion (and versus or).",
        "URL": "https://github.com/abhinavsingh/proxy.py/pull/482/commits/9b00093288237f5073c403f2c4f62acfdfa8ed46",
        "Tag": "['Patch']",
        "fix_commit_hash": "bff171ec26d826ae1d22d2466eaf9d8bdbf059d3"
    }
]