[{"repo_name": "pyca/pyopenssl", "CVE_ID": "CVE-2018-1000807", "Problem_Type": "CWE-416", "Description": "Python Cryptographic Authority pyopenssl version prior to version 17.5.0 contains a CWE-416: Use After Free vulnerability in X509 object handling that can result in Use after free can lead to possible denial of service or remote code execution.. This attack appear to be exploitable via Depends on the calling application and if it retains a reference to the memory.. This vulnerability appears to have been fixed in 17.5.0.", "URL": "https://github.com/pyca/pyopenssl/pull/723", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "e73818600065821d588af475b024f4eb518c3509", "inducing_commit_hash_pyszz": ["57051a53e154c2b401ab84d6f01c6512e6c7b346"]}, {"repo_name": "pyca/pyopenssl", "CVE_ID": "CVE-2018-1000808", "Problem_Type": "CWE-404", "Description": "Python Cryptographic Authority pyopenssl version Before 17.5.0 contains a CWE - 401 : Failure to Release Memory Before Removing Last Reference vulnerability in PKCS #12 Store that can result in Denial of service if memory runs low or is exhausted. This attack appear to be exploitable via Depends upon calling application, however it could be as simple as initiating a TLS connection. Anything that would cause the calling application to reload certificates from a PKCS #12 store.. This vulnerability appears to have been fixed in 17.5.0.", "URL": "https://github.com/pyca/pyopenssl/pull/723", "Tag": "['Patch', 'Third Party Advisory']", "fix_commit_hash": "e73818600065821d588af475b024f4eb518c3509", "inducing_commit_hash_pyszz": ["57051a53e154c2b401ab84d6f01c6512e6c7b346"]}]