[
    {
        "repo_name": "scipy/scipy",
        "CVE_ID": "CVE-2023-25399",
        "Problem_Type": "NVD-CWE-Other",
        "Description": "A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function.",
        "URL": "https://github.com/scipy/scipy/pull/16397",
        "Tag": "['Patch']"
    },
    {
        "repo_name": "scipy/scipy",
        "CVE_ID": "CVE-2023-29824",
        "Problem_Type": "CWE-416",
        "Description": "A use-after-free issue was discovered in Py_FindObjects() function in SciPy versions prior to 1.8.0. NOTE: the vendor and discoverer indicate that this is not a security issue.",
        "URL": "https://github.com/scipy/scipy/pull/15013",
        "Tag": "['Patch']"
    }
]